sudo: true
services: docker
language: python
os: linux
cache: pip
python:
  - "3.6"

install: "pip install -r motey-docker-image/requirements.txt"

script:
  - pycodestyle --ignore=E241,E501 motey/
  - pycodestyle --ignore=E241,E501 samples/
  - python3 -m unittest tests/capabilityengine/test_* tests/communication/test_* tests/models/test_* tests/orchestrator/test_* tests/repositories/test_* tests/utils/test_* tests/val/test_*

after_success:
  - if [[ "$TRAVIS_BRANCH" = "master" ]]; then
    docker build -t neoklosch/motey motey-docker-image;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push neoklosch/motey;
    fi
  - if [[ "$TRAVIS_BRANCH" = "master" ]]; then
    docker build -t neoklosch/motey-rpi motey-rpi-docker-image;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push neoklosch/motey-rpi;
    fi
