sudo: true
services:
  - docker

language: python

os:
  - linux

cache: pip

python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev

install: "pip install -r motey-docker-image/requirements.txt"

script:
  - pycodestyle --ignore=E241,E501 motey/
  - pycodestyle --ignore=E241,E501 samples/
  - python3 -m unittest tests/test_*.py


after_success:
  - if [[ "$TRAVIS_BRANCH" = "master" ]]; then
    docker --version;
    docker build -t neoklosch/motey motey-docker-image;
    docker tag neoklosch/motey:latest;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push neoklosch/motey;
    fi
